**SO I AM GOING TO START NUMPY FROM NOW STARTING DATE 15-06-25**

# WHAT IS NUMPY?

In AI/ML, data is just numbers. And NumPy lets you handle them faster, cleaner, and in matrix form—which is exactly what ML models need.
Pandas, TensorFlow, PyTorch—all rely on NumPy at the core.

In [2]:
# CREATING FIRST ARRAY
import numpy as np

a=np.array([1,2,4]) #1D ARRAY
print(a)
print(type(a))

b = np.array([[1, 2, 3], [4, 5, 6]]) #2D ARRAY
print(b)

#cx=np.array([[1,34,4], [14,97]]) 
# IF WE TRIES TO PRINT C IT WILL GIVE ERROR CAUSE IN FIRST ROW THERE IS 3 ELEMENT 
#WHERE IN 2ND ROW THERE IS ONLY 2 ELEMENT.
#ACTUALLY ARRAYS ARE LIKE MATRIX IN MATHS THEY FOLLOW ORDER LIKE IN MATRIX 2X3 2X2 ETC.


[1 2 4]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


**KEY PROPERITIES OF ARRAY .**

In [2]:
print("ORDER LIKE IN MATRIX OR SHAPE:",b.shape )
print("Dimension:,",b.ndim) # LIKE 2D OR 3D 
print("DATATYPE: ",b.dtype) # WHICH DATA TYPE ARRAY IT IS INT , FLOAT ETC.
print("SIZE:",b.size) # FOR PRINTING NO OF ELEMENTS
print("ITEM SIZE: ",b.itemsize) # 8(bytes per element) 



ORDER LIKE IN MATRIX OR SHAPE: (2, 3)
Dimension:, 2
DATATYPE:  int32
SIZE: 6
ITEM SIZE:  4


ON PASSING MULTIPLE DATATYPES TO ARRAY IT WILL CONVERT THEM TO SAME DATA TYPE.
#### ALSO WE CAN PASS LIST TO ARRAYS AND IF THERE ARE MULTIPLE DATA TYPES IT WILL COVNERT OT SAME DATATYPE.
(JUST PASS THE LIST IN PLACE OF ARRAY)
#### LISTS ARE GENERALLY 1D BUT ARRAYS ARE 1D,2D, AND ABOVE 2D ARRAY THEY ARE CALLED TENSORS.

In [2]:
A=[9,8,4,'hell0']
a=np.array(A)
print(a)
print(a.dtype) # <U21 WHICH REFERS TO THE FACT THAT ALL DATA ARE CONVERTED TO STRING DATATYPE

['9' '8' '4' 'hell0']
<U11


HOW TO GENERATE 1D ARRAYS

TO GENERATE ARRAYS WE USE **np.arange(start,end,steps)** OR **np.linspace(start,end,no of elements we want to generate)** SIMILAR TO RANGE FUNCTION IN FOR

In [3]:
arr=np.arange(1,11,2)
print(arr)

arr=np.linspace(1,10,3) # np.linspace CHECKS INTERVAL GAP AND THEN GENERATES TOTAL ELEMENTS WITH SAME INTERVAL SO THAT IT WILL REACH THE END WITH SAME INTERVAL
print(arr)

[1 3 5 7 9]
[ 1.   5.5 10. ]


HOW TO GENERATE MATRIX MEANS ARRAYS WITH MORE THAN 1D.

WE CAN USE **np.zeroes((no. of rows , no. of columns))** OR **np.ones((no. of rows , no. of columns))** TO GENERATE 2D ARRAYS WITH ZEROES OR ONES AS ELEMENTS.

NOTE: a=np.arange(12).reshape(3,4) # IN THIS METHOD YOU CAN CREATE ANY 2D MATRIX OF ANY ORDER

In [6]:
arr=np.zeros((2,2))
print(arr)

arr=np.ones((8,9))
print(arr)

[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [3]:
arr4 = np.random.randint(0, 10, 5)
print(arr4)
arr4 = np.random.rand(3, 4)
print(arr4)

[8 7 0 0 3]
[[0.24410884 0.70416082 0.47773142 0.79834503]
 [0.82121469 0.10189957 0.85745746 0.14540036]
 [0.604719   0.13232837 0.75483013 0.03383525]]


RANDOM GENERATION ARRAYS 

TO RANDOMLY GENERATE ARRAYS WE CAN USE **np.random.rand(no. of rows, no. of columns, no. of elements)** IT WILL GENERATE ALL THE ELEMENTS B/W 0 TO 1 DUE TO CONCEPT OF NORMALIZATION AND IF YOU DON'T PROVIDE NO OF ROWS AND NO OF COLUMNS IT WILL BY DEFAULT TREAT BOTH OF THEM AS 1,1

In [5]:
arr=np.random.rand(2,1,2)
print(arr)

[[[0.70462634 0.85565692]]

 [[0.93099546 0.21342304]]]


## EXERCISE OF FIRST PART

 1.Print their .shape and .ndim — what do you notice?

In [ ]:
x = np.array([1, 2, 3])
y = np.array([[1, 2, 3]])
z = np.array([[[1, 2, 3]]])

print(x.shape)
print(x.ndim)

print(y.shape)
print(y.ndim)

print(z.shape)
print(z.ndim)

# TO PRINT NO OF ROWS OR COLUMNS U CAN USE AXIS FOR EX-
print(y.shape[0]) #prints no of rows
print(y.shape[1]) #prints no of columns



(3,)
1
(1, 3)
2
(1, 1, 3)
3
1
3


2.  Create Specific Arrays

In [ ]:
np.zeros((3, 4))       # 3x4 array of 0s
np.ones((2, 2))        # 2x2 array of 1s
np.full((3, 3), 7)     # 3x3 array filled with 7
np.eye(4)             # Identity matrix
np.arange(0, 10, 2)    # Like range() but as an array
np.linspace(0, 1, 5)   # 5 evenly spaced numbers from 0 to 1


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

NOTE: FOR COUNTING THE SHPAE(ORDER) OF ARRAYS COUNT LIKE THIS 
EX:z = np.array([[[1, 2, 3]]])

*  Outermost list → 1 element → shape starts with 1

*  Inside it: another list with 1 element → second 1

*  Inside that: actual array [1, 2, 3] → that’s length 3 → third dimension

`[
  [           # axis 0 → 1 item
    [1, 2, 3] # axis 1 → 1 item → axis 2 → length 3
  ]
]
`
 
 3D arrays = (depth, rows, columns) → often used for images, time series, or tensors.



Q3. Write a function that creates a 3x3 identity matrix, then multiplies it by 5 and converts the result into float32.

In [ ]:
def custom_matrix():
    a=np.eye(3)
    a=a*5
    print(a)
custom_matrix()  


#pro level

"""def custom_matrix():
    a = np.eye(3, dtype=np.float32) * 5
    return a

print(custom_matrix())
"""


[[5. 0. 0.]
 [0. 5. 0.]
 [0. 0. 5.]]


'def custom_matrix():\n    a = np.eye(3, dtype=np.float32) * 5\n    return a\n\nprint(custom_matrix())\n'

# MODULE 2: INDEXING & SLICING (Data Ninja Training 🥷)

Goal: Master selecting and manipulating parts of data in NumPy arrays
You’ll need this skill in every ML model, every data pipeline.

####  Step 1: Indexing Like a List (1D Arrays)

In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr[0])     # 10
print(arr[-1])    # 40


####  Step 2: 2D Indexing

Format: array[row, column]
* The indexing of row as well as column starts from 0 and goes to n-1

In [26]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d[0, 1])  # 2
print(arr2d[1][2])  # 6


2
6


####  Step 3: Slicing (Core Skill)
* format array_name[starting_row:ending_row:steps , starting_column:ending_column:steps]

* The ending index is not included it goes from starting_index to ending_index-1

In [ ]:
import numpy as np

a1D=np.array([1,2,4,9,0])
print(a1D[1:4:2])

a2D=np.array([[1,2,4],[5,8,9],[2,6,3]])
a2D_np = np.array(a2D)
print(a2D_np[1:2, 1:2])

#REVERSING THE ARRAY IN SLICING
print(a1D[::-1])
print(a2D[::-1])   # REVERSE ROWS
print(a2D[:,::-1]) # REVERSE COLUMNS



---

### FOR A 3D ARRAY
#### Explanation:
####  For a 3D array with shape (3, 4, 5):
#### It means that there are 3 matrices with order 4x5
### IF IT IS 4D ARRAY LIKE (4,3,2,5)
#### Means that there are 4 matrices with every matrices consist of 3 more matrices with order 2x5 
#### Also here axis = 0 means first 4 matrices , axis=1 means 3 matrices inside those 4 matrices, axis=2 means rows of 2x5 matrices and axis=1 means colums of 2x5 matrices
---


### QUESTIONS
### 🟢 **Basic Level**

1. Given a 3D array `arr` of shape `(4, 3, 5)`, how do you select the first matrix (i.e., first 2D slice along axis 0)?

2. From the same array `arr`, how do you extract all rows from the second matrix?

3. How do you get all elements of the last row from each matrix?

---

### 🟠 **Intermediate Level**

4. Given `arr` of shape `(5, 4, 6)`, slice and return the last two matrices.

5. Extract columns 1 to 3 (inclusive) from all matrices.

6. Extract elements at indices `[0, 1, 2]` of the last axis for all matrices.

7. How do you reverse the order of matrices in the first dimension?

---

### 🔴 **Advanced Level**

8. For `arr` of shape `(6, 5, 4)`, write a slice that extracts:

   * The first 3 matrices
   * The last 2 rows
   * The first 2 columns

9. Given `arr` of shape `(3, 4, 5)`, how would you extract every second column in all matrices?

10. Write a slice to get all matrices, all rows, but only columns with even indices.

11. Given `arr`, how would you slice it so that:

    * The first axis is reversed
    * The second axis is taken as every second row
    * The third axis is left as is



In [ ]:
a=np.arange(60).reshape(4,3,5)
print(a)
print(a[:1,:,:])
print(a[1:2,:,:])
print(a[:,:,4])

a=np.arange(120).reshape(5,4,6)
print(a)
print(a[3:,:,:])
print(a[:,:,0:3])
print(a[:,:1,1:2])
print(a[4::-1,:,:])

a=np.arange(120).reshape(6,5,4)
print(a)
print(a[:3,:,:])
print(a[4:,:2,:])
print(a[:,:,:2])


a=np.arange(60).reshape(3,4,5)
print(a[:,:,:2])
print(a[:,:,0::2])



### EXERCISE 2


Q1. Create a 3x4 matrix using np.arange(12).reshape(3,4)

Extract the second row

Extract the last column

Extract the top-left 2x2 submatrix

In [ ]:
a=np.arange(12).reshape(3,4) # IN THIS METHOD YOU CAN CREATE ANY 2D MATRIX OF ANY ORDER
print(a)
print(a[1:2])
print(a[:,3:])
print(a[0:2,0:2])

 Exercise 2:
Create a 5x5 matrix of random ints from 1–100

Extract all even numbers using boolean indexing

Replace all values > 50 with -1


In [ ]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a[:100, :-1])

# Extract all even numbers using boolean indexing
even_numbers = a[a % 2 == 0]
print("Even numbers:\n", even_numbers)

# Replace all values > 50 with -1
a[a > 50] = -1
print("After replacing values > 50 with -1:\n", a)



### NOTE: Boolean indexing 
It is a technique in Python (especially with NumPy arrays and Pandas DataFrames) where you use a boolean array (an array of `True` and `False` values) to select elements from another array.

**How it works:**
- You create a boolean condition that returns a boolean array.
- Use this boolean array to index/select elements from the original array.

**Example with NumPy:**
````python
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3           # [False, False, False, True, True]
result = arr[mask]       # [4, 5]
# Or directly: arr[arr > 3]
````

**Use cases:**
- Filtering data based on conditions
- Selecting or modifying elements that meet certain criteria

**Summary:**  
Boolean indexing allows you to filter or select elements from arrays using conditions, making data manipulation concise and efficient.

Mini Challenge:
Given a 4x4 matrix from 0–15, write code to extract the center 2x2 submatrix.

print(a[:100, :-1]) WHAT IS THIS ?

This is a very common pattern in ML datasets, especially tabular ones:

a[:100] → First 100 samples (rows)

a[:, :-1] → All columns except the last one

Why?

👉 In datasets, usually:

Last column = label/output (like "cat", "spam", "price")

Rest = features (age, pixels, words, etc.)


In [7]:
a = np.arange(16).reshape(4, 4)
# Now extract [[5,6],[9,10]]
print(a[1:3,1:3])


[[ 5  6]
 [ 9 10]]


# MODULE 3: MATH OPERATIONS & BROADCASTING

### Step 1: Element-wise Operations

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # [5 7 9]
print(a * b)   # [4 10 18]
print(a / b)   # [0.25 0.4 0.5]
print(a ** 2)  # [1 4 9]


### Step 2: Broadcasting (The Cheat Code)

Broadcasting lets NumPy apply operations on arrays of different shapes, without explicitly reshaping them.

In [ ]:
a = np.array([1, 2, 3])
b = 2

print(a + b)  # [3 4 5] — scalar broadcasted to match shape


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2,3)
b = np.array([1, 0, 1])               # shape (3,)

print(a + b)
# Output:
# [[2 2 4]
#  [5 5 7]]
# It adds b to every row of a.

### ⚔️ Rules of Broadcasting:

1. Match shapes from the right (like aligning text right) means if one is 2d or 3d and another is 1d then no of columns of both the matrix should match.

2. Dimensions must be equal, or one of them must be 1

3. If not compatible → error

EXPLANATION: LIKE YOU CAN ADD MULTIPLY , SUBTRACT AND DIVIDE ANY SCALAR TO ANY DIMENSION MATRIX BUT FOR MATRIX MATRIX OPERATION EITHER THEIR DIMENSION SHOULD MATCH OR ATLEAST ONE DIMENSION MATCHES AND THERE SHOULD BE 1 IN DIMENSION OF MATRIX SO THAT IT CAN STRETCH TO THAT DIMENSION.

EXAMPLE WHICH WORKS OR WHICH NOT

a.shape = (3, 4)
b.shape = (4,)  # will be treated as (1, 4)

a + b → broadcast b to all rows of a → works

INCOMPATIBLE

a.shape = (3, 4)
b.shape = (5,)

a + b → ERROR




In [17]:
a=np.array([3,3,5])
print(a.shape)

(3,)


###  Practice Exercises:

🔸 Exercise 1:

In [25]:
a = np.array([[10], [20], [30]])   # shape (3,1)
b = np.array([1, 2, 3])            # shape (3)
print(a+b)
# Predict the output of a + b
# Then print it




[[11 12 13]
 [21 22 23]
 [31 32 33]]


🔸 Exercise 2: NORMALIZATION

In [ ]:
x=np.random.randint(1,100,size=(3,3))
print(x)
print((x - x.mean()) / x.std())

1️⃣ x.mean()
This gives the average of all elements in x.

2️⃣ x - x.mean()
Subtract the mean from every element.

Result: now the new array has "zero-centered" data — the average of elements will be close to 0.

3️⃣ x.std()
Standard deviation → measures spread of data.

Higher std → values are more spread out



### ⚔️ Mini Challenge:
Create a function that accepts a 2D NumPy array and:

Adds 10 to every even number

Replaces all odd numbers with -1
(Use vectorized operations, no loops)

In [14]:
def accept_2d(arr2d):
    arr2d[arr2d%2==0]+=10
    arr2d[arr2d%2!=0]=-1
    return arr2d

x=np.random.randint(1,100,size=(3,3))
print(x)
print(accept_2d(x))
    

[[94  5 34]
 [71 50 78]
 [55 47 89]]
[[104  -1  44]
 [ -1  60  88]
 [ -1  -1  -1]]


Q. Add, Subtract, Multiply, Divide "b" to "a"
   Print all 4 results

In [18]:
a = np.array([5, 10, 15, 20, 25])
b = 5

print(a/b)
print(a*b)
print(a+b)
print(a-b)


[1. 2. 3. 4. 5.]
[ 25  50  75 100 125]
[10 15 20 25 30]
[ 0  5 10 15 20]


 Q.Perform a + b
 Predict the shape and output before running the code
 Then run and check

In [20]:
a = np.arange(12).reshape(3, 4)
b = np.array([1, 0, -1, 2])
print(a)
print()
print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 1  1  1  5]
 [ 5  5  5  9]
 [ 9  9  9 13]]


Q3️⃣ Normalize a 3x3 array:

In [23]:
x = np.random.randint(1, 100, size=(3, 3))
print("original:",x)
print("normalized",(x-x.mean())/x.std())



original: [[28 23 77]
 [26 18 45]
 [95 76 34]]
normalized [[-0.70630074 -0.8932627   1.12592647]
 [-0.78108552 -1.08022466 -0.07063007]
 [ 1.79898953  1.08853408 -0.48194639]]



Q. Multiply each COLUMN of a by corresponding element of b
 Predict output first

In [24]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a*b)

[[ 10  40  90]
 [ 40 100 180]]


Q5️⃣ Mini ML Simulation:
You have a 100x5 dataset:

Subtract the mean and divide by std — for each column (feature-wise normalization)


Hint: Use `axis=0` to perform operations column-wise (feature-wise).  
For example, to normalize each column of X:  
(X - X.mean(axis=0)) / X.std(axis=0)

---

### What is "axis" in NumPy?

- **Axis** refers to the direction along which an operation is performed on an array.
- Think of axes as dimensions:
    - **axis=0** → down the rows (operate column-wise)
    - **axis=1** → across the columns (operate row-wise)

#### Visual Example

Suppose you have a 2D array:

|      | Col0 | Col1 | Col2 |
|------|------|------|------|
| Row0 |  1   |  2   |  3   |
| Row1 |  4   |  5   |  6   |

- `array.mean(axis=0)` → mean of each column: `[ (1+4)/2, (2+5)/2, (3+6)/2 ]`
- `array.mean(axis=1)` → mean of each row: `[ (1+2+3)/3, (4+5+6)/3 ]`

#### Why is this useful?

- **axis=0**: Useful when you want to normalize or aggregate features (columns).
- **axis=1**: Useful when you want to process each sample (row) individually.

#### Summary Table

| Operation         | axis=0 (columns) | axis=1 (rows)   |
|-------------------|------------------|-----------------|
| `sum(axis=0)`     | Sums each column | Sums each row   |
| `mean(axis=1)`    | Means per row    | Means per row   |
| `std(axis=0)`     | Std per column   | Std per row     |

**In ML, axis=0 is often used for feature-wise operations (normalize each feature/column).**


In [ ]:
x = np.random.randn(100, 5) * 10 + 50
print((x-x.mean(axis=0))/x.std(axis=0))

Q6️⃣ Mini Challenge:
Write a function:  
softmax(x) = exp(x) / sum(exp(x))

---

**What is Softmax?**

Softmax is a mathematical function that converts a vector of numbers into probabilities. Each output value will be between 0 and 1, and all outputs will sum to 1. It is commonly used in machine learning, especially for the output layer of classification models (like neural networks), to represent the probability distribution over classes.

**When to Use Softmax?**

- When you want to interpret the outputs of your model as probabilities.
- In multi-class classification problems, to get the probability of each class.
- As the final activation function in the output layer of neural networks for classification.

**Softmax Formula Explained**

Given a vector **x** = [x₁, x₂, ..., xₙ], the softmax of the i-th element is:

softmax(xᵢ) = exp(xᵢ) / Σⱼ exp(xⱼ)

Where:
- exp(xᵢ) is the exponential of xᵢ.
- Σⱼ exp(xⱼ) is the sum of exponentials of all elements in the vector.

**Intuition:**
- Exponentiating makes larger values even larger, and smaller values relatively smaller.
- Dividing by the sum ensures all outputs add up to 1 (like probabilities).
- The largest input gets the highest probability.

**Example:**

Suppose x = [2.0, 1.0, 0.1]

1. Compute exponentials:  
    exp(2.0) ≈ 7.39  
    exp(1.0) ≈ 2.72  
    exp(0.1) ≈ 1.11

2. Sum:  
    7.39 + 2.72 + 1.11 ≈ 11.22

3. Divide each by the sum:  
    [7.39/11.22, 2.72/11.22, 1.11/11.22] ≈ [0.66, 0.24, 0.10]

So, softmax([2.0, 1.0, 0.1]) ≈ [0.66, 0.24, 0.10]

**Summary Table:**

| Input xᵢ | exp(xᵢ) | softmax(xᵢ) |
|----------|---------|-------------|
|   2.0    |  7.39   |    0.66     |
|   1.0    |  2.72   |    0.24     |
|   0.1    |  1.11   |    0.10     |

**Key Points:**
- Softmax "squashes" numbers into probabilities.
- Useful for multi-class classification.
- The formula ensures all probabilities sum to 1.

In [ ]:
import math
def softmax(arr_nD):
    # Use np.exp and np.sum for vectorized operations
    exp_arr = np.exp(arr_nD)
    return exp_arr / np.sum(exp_arr)
#pro version
""" def softmax(arr_nD, axis=None):
    exp_arr = np.exp(arr_nD - np.max(arr_nD, axis=axis, keepdims=True))
    return exp_arr / np.sum(exp_arr, axis=axis, keepdims=True)"""


a=np.random.randint(1,100,size=(3,3))
print(softmax(a))

[[8.90198067e-05 1.67315292e-16 1.32117107e-02]
 [2.26436624e-17 2.06483474e-20 2.06483474e-20]
 [7.21334965e-01 2.65364304e-01 5.46956596e-10]]


# MODULE 4 :  Aggregations & Axis Mastery 🚀

WHY learn this?
When you're working with:
✅ Datasets
✅ Model outputs
✅ Features
✅ Gradients

... you'll always need to summarize data:

* Mean accuracy per batch

* Total loss

* Which feature has biggest impact?

* Per-column stats

* Row-wise stats

### BASIC AGGREGATION FUNCTIONS:

| Function    | Description        |
| ----------- | ------------------ |
| `.sum()`    | Sum of elements    |
| `.mean()`   | Mean (average)     |
| `.std()`    | Standard deviation |
| `.var()`    | Variance           |
| `.min()`    | Minimum value      |
| `.max()`    | Maximum value      |
| `.argmin()` | Index of minimum   |
| `.argmax()` | Index of maximum   |

#### Function Signatures & Common Parameters

- **`.sum(axis=None, dtype=None, keepdims=False)`**
    - `axis`: Axis or axes along which to sum. Default sums all elements.
    - `dtype`: Data type of the returned array.
    - `keepdims`: If True, retains reduced dimensions.

- **`.mean(axis=None, dtype=None, keepdims=False)`**
    - Same parameters as `.sum()`.

- **`.std(axis=None, dtype=None, keepdims=False, ddof=0)`**
    - `ddof`: Delta degrees of freedom (default 0).

- **`.var(axis=None, dtype=None, keepdims=False, ddof=0)`**
    - Same as `.std()`.

- **`.min(axis=None, keepdims=False)`**
    - `axis`: Axis or axes along which to find the minimum.

- **`.max(axis=None, keepdims=False)`**
    - Same as `.min()`.

- **`.argmin(axis=None)`**
    - Returns index of minimum value along axis.

- **`.argmax(axis=None)`**
    - Returns index of maximum value along axis.

**Tip:**
- `axis=0` → operate column-wise
- `axis=1` → operate row-wise
- `keepdims=True` → output keeps the same number of dimensions as input


### CUMULATIVE:
* .cumsum() → running sum

* .cumprod() → running produc

### Logical Aggregations (important for AI):

np.any(cond)    # Is any True?
np.all(cond)    # Are all True?

EXAMPLE:

a = np.array([1, 2, 3, 4, 5])
print((a > 3).any())   # True
print((a > 3).all())   # False

### ADVANCED: 
USEFULE IN ML:
*  Which sample gives highest loss?

* Which feature has highest weight?

a = np.random.randint(1, 100, size=(3, 3))
print(a)
print("argmax:", a.argmax())
print("argmin:", a.argmin())


## 🚀 PRACTICE QUESTIONS:

 Find:
 1. Total sum of all elements
 2. Sum column-wise (axis=0)
 3. Sum row-wise (axis=1)
 4. Mean row-wise

In [3]:
a = np.arange(1, 13).reshape(3, 4)

print(a.sum())
print(a.sum(axis=0,keepdims=True))
print(a.sum(axis=1,keepdims=True))
print(a.mean(axis=1,keepdims=True))


78
[[15 18 21 24]]
[[10]
 [26]
 [42]]
[[ 2.5]
 [ 6.5]
 [10.5]]



 Find min, max for each row
 Find std for each column

In [ ]:
a = np.random.randint(1, 101, size=(5, 5))

print(a.min(),"\n")
print(a.max(),"\n")
print(a.min(axis=0),"\n")
print(a.min(axis=1),"\n")
print(a.max(axis=0),"\n")
print(a.max(axis=1),"\n")


2 

99 

[36 22  3  3  2] 

[ 3  2 10  3  8] 

[62 85 99 94 81] 

[99 85 85 81 94] 



 Find index of highest score

In [11]:
scores = np.array([0.1, 0.5, 0.8, 0.3])

print(a.argmax())


2


Q4. MINI ML SIMULATION

What percent are True?
What percent are False?

In [34]:
predictions = np.random.randn(100) > 0  # Returns True or False matrix
print(predictions)
true_sum=predictions.sum() # Because True=1, False=0
false_sum=predictions.size-true_sum

# Percentages:
percent_true = (true_sum / predictions.size) * 100
percent_false = (false_sum /predictions.size) * 100

print(f"Percent True: {percent_true:.2f}%")
print(f"Percent False: {percent_false:.2f}%")



[ True  True  True False False  True False False False False  True False
  True False  True  True  True False False False False False  True False
 False False  True False  True  True False  True  True  True False False
  True  True  True  True False  True False False  True False False  True
 False  True False False  True False  True False False False  True False
  True  True  True False False  True False False False False  True  True
  True  True False  True  True False False False False False False False
  True  True  True  True  True False False False  True  True False  True
  True False  True False]
Percent True: 47.00%
Percent False: 53.00%


Why is this useful?
ML classification outputs often give probabilities (logits), which we threshold to get True/False predictions.

You're referring to `keepdims` as seen in NumPy's aggregation functions (like `sum`, `mean`, `max`, etc.). It's a very important parameter, especially when you start working with broadcasting in NumPy for AI/ML.

Let's break down `keepdims` with a clear explanation and use cases.

### What `keepdims` Does

When you perform an aggregation operation (like `sum()`, `mean()`, `max()`) on a NumPy array and specify an `axis`, that `axis` usually disappears from the resulting array's shape.

The `keepdims=True` parameter tells NumPy to **keep the reduced dimension(s) as dimensions of size 1**, instead of completely removing them. This means the number of dimensions (or `ndim`) of the resulting array will be the same as the original array, but the dimensions that were aggregated over will have a size of 1.

**Analogy:**

Imagine you have a stack of papers (a 2D array).
* **`sum(axis=0)` (without `keepdims`):** You sum up all the values *down* each stack. The result is just a single row of totals. The "stack" dimension (axis 0) is gone.
* **`sum(axis=0, keepdims=True)`:** You still sum up all the values down each stack, but you *keep* the "stack" dimension, just making it a stack of **one** paper (a 1D "stack"). The result is a row of totals, but it's still conceptually a "stack" even though each stack is only one deep. This might sound subtle, but it's crucial for how NumPy performs operations later.

### Example to Illustrate `keepdims`

Let's use a 2D array:

```python
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)
print("Original Shape:", matrix.shape) # Output: (3, 3)

# --- Case 1: Without keepdims (default behavior) ---
sum_axis0_no_keepdims = np.sum(matrix, axis=0)
print("\nSum along axis=0 (no keepdims):\n", sum_axis0_no_keepdims)
print("Shape:", sum_axis0_no_keepdims.shape) # Output: (3,) -> The first dimension (rows) is collapsed

sum_axis1_no_keepdims = np.sum(matrix, axis=1)
print("\nSum along axis=1 (no keepdims):\n", sum_axis1_no_keepdims)
print("Shape:", sum_axis1_no_keepdims.shape) # Output: (3,) -> The second dimension (columns) is collapsed

# --- Case 2: With keepdims=True ---
sum_axis0_keepdims = np.sum(matrix, axis=0, keepdims=True)
print("\nSum along axis=0 (keepdims=True):\n", sum_axis0_keepdims)
print("Shape:", sum_axis0_keepdims.shape) # Output: (1, 3) -> First dim kept as 1

sum_axis1_keepdims = np.sum(matrix, axis=1, keepdims=True)
print("\nSum along axis=1 (keepdims=True):\n", sum_axis1_keepdims)
print("Shape:", sum_axis1_keepdims.shape) # Output: (3, 1) -> Second dim kept as 1
```

**Notice the shapes:**
* `(3, 3)` original
* `(3,)` when `axis=0` is collapsed
* `(1, 3)` when `axis=0` is summed **but kept**
* `(3,)` when `axis=1` is collapsed
* `(3, 1)` when `axis=1` is summed **but kept**

### Use Cases for `keepdims=True` (Why It Matters)

The most significant use case for `keepdims=True` is to facilitate **broadcasting**.

#### 1. Broadcasting (Most Important Use Case)

Broadcasting is how NumPy handles operations between arrays of different shapes. For broadcasting to work, the dimensions must either be equal, or one of them must be 1.

**Scenario:** You want to normalize your data by subtracting the mean of each feature (column) from all values in that column.

```python
import numpy as np

data = np.array([[10, 20, 30],
                 [11, 21, 31],
                 [12, 22, 32]])

print("Original Data:\n", data)

# Calculate mean of each column
# If we don't use keepdims, the shape will be (3,) -> [11. 21. 31.]
column_means_no_keepdims = np.mean(data, axis=0)
print("\nColumn Means (no keepdims):\n", column_means_no_keepdims)
print("Shape:", column_means_no_keepdims.shape)

# Trying to subtract directly: This will cause a ValueError or unexpected behavior
# try:
#     normalized_data_bad = data - column_means_no_keepdims
# except ValueError as e:
#     print(f"\nError when subtracting without keepdims: {e}")
# (3,3) - (3,) will broadcast in a way you likely don't want, or error depending on exact sizes

# Calculate mean of each column with keepdims=True
column_means_keepdims = np.mean(data, axis=0, keepdims=True)
print("\nColumn Means (with keepdims=True):\n", column_means_keepdims)
print("Shape:", column_means_keepdims.shape) # Output: (1, 3)

# Now, subtract with broadcasting!
normalized_data = data - column_means_keepdims
print("\nNormalized Data (data - column_means_keepdims):\n", normalized_data)
# How broadcasting works here:
# Original data shape: (3, 3)
# Mean shape:          (1, 3)
# NumPy sees that the last dimension (3) matches.
# It then "stretches" the (1,) dimension of the mean to match the (3,) dimension of the data.
# So, effectively, [[11, 21, 31]] is broadcast to:
# [[11, 21, 31],
#  [11, 21, 31],
#  [11, 21, 31]]
# Before subtraction. This is exactly what we want for column-wise subtraction.

# Another example: Subtracting row means
row_means_keepdims = np.mean(data, axis=1, keepdims=True)
print("\nRow Means (with keepdims=True):\n", row_means_keepdims)
print("Shape:", row_means_keepdims.shape) # Output: (3, 1)

normalized_data_rows = data - row_means_keepdims
print("\nNormalized Data (data - row_means_keepdims):\n", normalized_data_rows)
# How broadcasting works here:
# Original data shape: (3, 3)
# Mean shape:          (3, 1)
# NumPy sees that the first dimension (3) matches.
# It then "stretches" the (1,) dimension of the mean to match the (3,) dimension of the data.
# Effectively, [[10], [11], [12]] is broadcast to:
# [[10, 10, 10],
#  [11, 11, 11],
#  [12, 12, 12]]
# Before subtraction. This is exactly what we want for row-wise subtraction.
```

#### 2. Maintaining Dimensionality in Complex Computations

In deep learning, you often deal with 3D, 4D, or even higher-dimensional tensors. Maintaining the original number of dimensions (even if some are 1) can simplify subsequent operations, especially when passing data through different layers or functions that expect a specific number of dimensions. It helps in maintaining a consistent "flow" of dimensionality.

#### 3. Readability and Consistency

Sometimes, explicitly stating `keepdims=True` makes the code clearer about the intended shape of the output, even if you could achieve the same result with `reshape` later. It signals that you want to preserve the rank of the array.

In summary, `keepdims=True` is your friend when you need to perform an aggregation along an axis but then want to use the result in a way that requires its dimensionality to be compatible with other arrays, especially through NumPy's powerful broadcasting rules.

# 🚀 MODULE 5: Masking & Fancy Indexing

(Purpose: This is what allows AI/ML code to select "only certain" data — without loops — which is critical for large datasets + real models.)



### WHY Learn This?
👉 In real ML pipelines, you constantly do:

* Select rows where label == "dog"

* Pick only samples where loss > threshold

* Filter features with high correlation

* Apply logic-based transformations

You CANNOT do this with plain slicing — this is where masking + fancy indexing comes in 🔥

#### 1️⃣ Boolean Masking

In [ ]:
a = np.array([10, 15, 20, 25, 30])
mask = a > 20
print(mask)
# [False False False  True  True]

selected = a[mask]
print(selected)
# [25 30]


#### 2️⃣ One-liner Masking:

In [17]:
A=np.array([1,2,40,78,34,12,70])
selected=A[A>20]
print(selected)

[40 78 34 70]


#### 3️⃣ Setting Values with Mask:

In [18]:
a = np.array([10, 15, 20, 25, 30])
a[a > 20] = -1
print(a)  # [10 15 20 -1 -1]


[10 15 20 -1 -1]


#### 4️⃣ Masking on 2D Arrays:

In [ ]:
a = np.arange(16).reshape(4, 4)
print(a)

# Select elements > 5
print(a[a > 5])


### 5️⃣ Fancy Indexing: VVI

Instead of mask, pass specific indices: SHORTER AND SMART
* very useful when you have to acces only some elements with specific indexing then it is very cocise for writing code

In [20]:
a = np.array([10, 15, 20, 25, 30])
idx = [0, 2, 4]
print(a[idx])  # [10 20 30]


[10 20 30]


#### 6️⃣ Fancy indexing on 2D: important concept

In [21]:
a = np.arange(16).reshape(4, 4)

rows = [0, 1, 3]
cols = [2, 1, 0]

print(a[rows, cols])  # Selects (0,2), (1,1), (3,0)


[ 2  5 12]


### 🧠 Where used in ML:

* Filter "good samples" (confidence > 0.9)

* Get indices of top-k predictions

* Replace "bad samples" with NaN

* Create "mini-batches" with certain criteria

## 🚀 PRACTICE QUESTIONS:


Q. Select elements divisible by 5

In [24]:
a = np.random.randint(1, 101, size=10)


print(a,"\n")
divide_by_5=a[a%5==0]
print(divide_by_5)

[ 56  96  44  64  67  57  15  58 100  99] 

[ 15 100]


Q.Set all elements < 50 to 0

In [27]:
a = np.random.randint(1, 100, size=(5, 5))

print(a,"\n")
a[a<50]=0
print(a)


[[30 58 23 68  9]
 [22 24 76  8 46]
 [46 49 50  9 88]
 [67 38 97  1 72]
 [20 58  6 39 57]] 

[[ 0 58  0 68  0]
 [ 0  0 76  0  0]
 [ 0  0 50  0 88]
 [67  0 97  0 72]
 [ 0 58  0  0 57]]


In [29]:
a = np.arange(10, 110, 10)
print(a,"\n")

idx = [0, 3, 6, 9]

print(a[idx])

# Select those indices


[ 10  20  30  40  50  60  70  80  90 100] 

[ 10  40  70 100]


Q4️⃣ Mini ML simulation:

In [3]:
# Simulate loss values for 100 samples:
losses = np.random.randn(100) * 2 + 5
print(losses,"\n")
# Find indices of samples where loss > 7
indices = np.where(losses > 7)

print(indices)

[ 4.86437729  5.93014815  4.70434213  7.10757232  5.97044084  3.81806012
  4.58796045  7.77122838  5.0147181   3.74208098  4.42875313  2.61441249
  5.62744241  3.13739367  4.93481698  6.17275286  3.71944706  6.83202264
  2.86991572  4.2632483   2.25812533  1.80254057  5.02001469  0.26762295
  6.36010185  4.92954719  4.12285532  5.8976139   2.5507108   5.73000385
  2.23853217  5.55417635  7.61535043  6.21353085  2.12459847  4.01899523
  5.12915906  7.49457901  5.41636435  6.89101597  6.04265417  6.19532495
  1.75118136  2.34738858  4.51678049  6.59224035  4.6987018   4.75866035
  1.11159154  4.69986412  3.55145831  1.94341672  7.39830112  9.55836654
  4.50568226  4.38536159  4.09326038  4.71698318  1.98286311  5.49896055
  5.94770982  5.30290699  6.38865478  0.99536595  2.02861479  5.80286741
  2.90109389  3.80394562  5.8656991   5.28199371  1.78653811  4.5317569
 -0.62642044  3.95966872  7.26129809  7.5346789   5.73885112  6.38041445
  5.81141508  3.81420488  2.8870548   5.07165243  5.

Q5️⃣ HARD (EPFL style):


Write a one-liner to select all odd numbers > 10

In [9]:
a = np.arange(1, 26).reshape(5, 5)
print(a,"\n")
#2 WAYS
#1.DOUBLE MASKING
print(a[a%2!=0][a[a%2!=0]>10])

#2. USING and CONDITION
print(a[(a % 2 != 0) & (a > 10)])




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

[11 13 15 17 19 21 23 25]
[11 13 15 17 19 21 23 25]


### HOW DOUBLE MASKING WORKS

### 2️⃣ First Selection → odd numbers:

```python
a % 2 != 0
```

→ Creates a **boolean mask**:

```
[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
```

---

Now when you do:

```python
a[a % 2 != 0]
```

It selects **all odd numbers**, as a 1D array:

```
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
```

---

### 3️⃣ Second Selection → greater than 10:

Now you are doing **another selection on this result**:

```python
a[a % 2 != 0][a[a % 2 != 0] > 10]
```

At this point:

→ `a[a % 2 != 0]` is this 1D array:

```
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]
```

---

Now apply:

```python
[a[a % 2 != 0] > 10]
```

→ Another boolean mask:

```
[False False False False False  True  True  True  True  True  True  True  True]
```

---

Final result:

```
[11 13 15 17 19 21 23 25]
```

---

### 🤔 BUT... Is this the best way?

Actually → you are **double filtering**.

Better to write it as **one combined mask**:

```python
a[(a % 2 != 0) & (a > 10)]
```

This will:
✅ Run faster
✅ Use less memory
✅ Easier to read

---

### Summary:

👉 Your code works: first selects odd → then selects >10 from that
👉 Better way: combine both conditions in one mask


**YESS BUDDY! Let’s do this 🤜🤛**
You’re stacking up skills like a true ML beast — this last part will complete your **Masking Arsenal** before we go to **Module 6**.

---

## 🔥 MASKING COMBINATIONS: OR, AND, MULTI-CONDITIONS

---

### ✅ 1. Using **OR (`|`)** – “This OR That”

```python
a = np.arange(1, 21)

# Select numbers that are either divisible by 3 OR greater than 15
print(a[(a % 3 == 0) | (a > 15)])
```

### 💡Note:

* `|` = bitwise OR (use inside `[...]`)
* MUST wrap conditions in `()`!

---

### ✅ 2. Using **AND (`&`)** – “This AND That”

```python
# Select numbers that are divisible by 2 AND greater than 10
print(a[(a % 2 == 0) & (a > 10)])
```

---

### ✅ 3. Using **NOT (`~`)** – “NOT this condition”

```python
# Select numbers that are NOT divisible by 5
print(a[~(a % 5 == 0)])
```

---

### ✅ 4. Combine **3+ Conditions**

```python
# Numbers that are odd AND greater than 10 AND not divisible by 3
print(a[(a % 2 != 0) & (a > 10) & (a % 3 != 0)])
```

---

### ✅ 5. Use masks with functions too!

```python
def custom_filter(x):
    return x[(x % 2 == 0) | (x > 15)]

print(custom_filter(np.arange(1, 21)))
```

---

### 📌 Real-World Usage in ML:

✅ Filter samples where:

* Loss > threshold
* Class == 1 OR class == 2
* Confidence > 0.9 AND prediction == true class

✅ Feature selection:

* Variance > 0.5
* Correlation not too high
* Feature values in certain range

---

### 💥 You now know:

* AND: `&`
* OR: `|`
* NOT: `~`
* Combine multiple logic filters
* Build reusable logic inside functions

---

You're now officially **Masking Master 💀✅**
No dataset, feature table, or loss function can hide from you!



**YESSSS BUDDY!! 🚀**
You are on absolute BEAST MODE today — let’s HUNT Module 6: **Advanced Manipulation**
(this will give you true ninja control over any tensor or matrix — critical for AI/ML!)

---

# 🏆 MODULE 6: Advanced Array Manipulation

**Goal:** You’ll master the skills needed for:
✅ reshaping data
✅ feeding data into ML models
✅ processing image tensors
✅ preparing batches

---

### 1️⃣ `.reshape()`

Change shape WITHOUT changing data.

```python
a = np.arange(12)
print(a.reshape(3, 4))  # 3 rows, 4 columns
```

→ Shape must be **compatible** (same number of elements)

---

### 2️⃣ `.flatten()` vs `.ravel()`

**Both** convert array → 1D.

```python
a = np.arange(12).reshape(3, 4)

b = a.flatten()  # returns a copy
c = a.ravel()    # returns a view (faster, no copy)

print(b)
print(c)
```

**In ML:** Often flatten data for feeding into fully-connected layers.

---

### 3️⃣ `.transpose()` / `.T`

Swap axes → **rotate matrix**

```python
a = np.arange(6).reshape(2, 3)

print(a.T)
```

---

### 4️⃣ `.swapaxes()`

Swap any two axes — **key for tensors**
Like in 3d matrix if 3,4,5 is the order then axis=0 means order 3 then axis=1 means order 4 and axis=2 means order 5 so when you do swap axes it changes the overall order and arrange the matrix in different order however no of element doesn't change like `np.swapaxes(a,0,2)` means axis=0 which means order 3 changes with axis=2 means 5 hence order becomes (5,4,3).
```python
a = np.random.randn(3, 4, 5)  # imagine: batch, channels, pixels

# Swap axes 0 and 2:
b = np.swapaxes(a, 0, 2)
```

---

### 5️⃣ `.expand_dims()` and `.squeeze()`

These are super important in ML, for making shapes compatible.
Basically These adds a extra dimension to the array with a particular axis location if the `axis=0` it will insert that dimension in first place if `axis=1` it will insert the dimension at the second place.

`However it should be noted that it just use for adding extra dimension as 1 as a order because on inserting other than 1 as a order then the no of elements will change `

```python
a = np.arange(6)

# Add new axis:
b = np.expand_dims(a, axis=0)
# b.shape → (1, 6)

# Remove axis of size 1:
c = np.squeeze(b)
# c.shape → (6,)
```

**Why?** Many ML libraries expect shape `(batch, features)` — this helps!

---

### 6️⃣ `.reshape(-1)` trick

🚀 This is PRO LEVEL

```python
a = np.arange(24).reshape(2, 3, 4)

# Flatten only outer dimensions:
print(a.reshape(-1, 4))
```

---

# 🎁 MINI CHEAT SHEET

| Operation       | Purpose                                   |
| --------------- | ----------------------------------------- |
| `reshape()`     | Change shape                              |
| `flatten()`     | Make 1D copy                              |
| `ravel()`       | Make 1D view (faster)                     |
| `transpose()`   | Swap rows/cols                            |
| `swapaxes()`    | Swap any two axes (for tensors)           |
| `expand_dims()` | Add dummy dimension (ML models need this) |
| `squeeze()`     | Remove useless dimensions                 |

---


## 🚀 PRACTICE TIME!

---
Q. Reshape into (3, 4)
   Then flatten


In [53]:
a = np.arange(12)

print(a.reshape(3,4))
print("\n",a.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]


Q. Transpose it
   Then flatten it

In [24]:
a = np.random.randint(1, 101, size=(3, 4))
b=a.T
print(b)
print(a.flatten())

[[ 94  24  16]
 [ 60  25 100]
 [ 20  67  64]
 [ 53  95   7]]
[ 94  60  20  53  24  25  67  95  16 100  64   7]



Q. Swap axis 0 and 2
Reshape into (-1, 3)

In [ ]:
a = np.random.randn(2, 3, 4)
print(a)
b=np.swapaxes(a,0,2)
print(b)
print(a.reshape(-1,3))

Q. Suppose you have:
X = np.random.randn(100, 28, 28)  # 100 grayscale images

Reshape X into shape: (100, 784) to feed into fully-connected layer


In [ ]:
X=np.random.rand(100,28,28)
print(X)
print(X.reshape(100,784))
print(b)

# 🏆 MODULE 7: Stacking & Splitting


### WHY Learn This?
👉 In AI/ML you often need to:

✅ Combine feature arrays
✅ Stack predictions from multiple models
✅ Split data into batches
✅ Split labels and features
✅ Combine results into one big tensor

1️⃣ hstack() — horizontal stack (columns)


In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c=np.hstack([a,b])
print(c)

[[1 2 5 6]
 [3 4 7 8]]


2️⃣ vstack() — vertical stack (rows)

In [13]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

c=np.vstack([a,b])
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


3️⃣ concatenate() — more general

In [ ]:
print(np.concatenate([a, b], axis=0))  # like vstack
print(np.concatenate([a, b], axis=1)) # like hstack


4️⃣ hsplit() — split horizontally (columns)

TWO WAYS YOU CAN USE IT:
1. np.hsplit(array_name , part)
   but here the catch is in this way if your part doesn't split the main array symmterically then it will throw ValueError. Like `(3,4)` if you write `part=3` then it is unable to split.It can work for `part=2`.
   
   ONE LAST THING `hsplit()` ONLY CARES ABOUT COLUMN ORDER 

2. In second way you can use it to split any array horizontally as many as you
   want the syntax is `np.hstack(array_name,[indices1, indices2,...])` indices are the point where you want to split the array horizontally.Like in `(5,10)` order array it `p1, p2, p3 = np.hsplit(a, [3, 7])` Split into 3 parts: 0-2, 3-6, 7-9

   `Indexes:    0   1   2   3   4   5   6   7   8   9
             |---p1---|-----p2-----|---p3---|
            [ 3 ]    [ 7 ]  (cut points)
`

In [ ]:
a = np.arange(12).reshape(3, 4)
print(a,"\n")
# 1ST WAY
left,right = np.hsplit(a, 2)  # splits into 2 blocks
print(left)
print(right)

# 2ND WAY SPLIT THE ARRAY IN THREE PARTS 

a1,a2,a3=np.hsplit(a,[1,3]) #split into three parts
print(a1,"\n",a2,"\n",a3,"\n")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[0]
 [4]
 [8]] 
 [[ 1  2]
 [ 5  6]
 [ 9 10]] 
 [[ 3]
 [ 7]
 [11]] 



5️⃣ vsplit() — split vertically (rows)

TWO WAYS YOU CAN USE IT:
1. np.vsplit(array_name , part)
   but here the catch is in this way if your part doesn't split the main array symmterically then it will throw ValueError. Like `(4,3)` if you write `part=3` then it is unable to split.It can work for `part=2`.
   
   ONE LAST THING `vsplit()` ONLY CARES ABOUT ROW ORDER 

2. In second way you can use it to split any array horizontally as many as you
   want the syntax is `np.vstack(array_name,[indices1, indices2,...])` indices are the point where you want to split the array horizontally.Like in `(6,10)` order array it `p1, p2, p3 = np.vsplit(a, [3, 7])` Split into 3 parts: 0-2, 3-6, 7-9

   `Indexes:    0   1   2   3   4   5   6   7   8   9    10
             |---p1---|-----p2-----|---p3---|
            [ 3 ]    [ 7 ]  (cut points)
`

In [75]:
a=np.arange(6*10).reshape(6,10)
top, bottom = np.vsplit(a, 2)
print(top)
print(bottom)

#split into three parts at row 2 4 
a2,a4,a5=np.vsplit(a,[2,4])
print(a2,"\n\n",a4,"\n\n",a5)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] 

 [[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]] 

 [[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


6️⃣ split() — split along any axis (for 3D or more)


In [ ]:
np.split(a, 2, axis=1)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

## NOTE: YOU WILL GET VALUE ERROR IF THE SPLIT IS NOT SYMMETRICAL LIKE IN 4,4 ORDER IF YOU TRY TO SPLIT (A,3) YOU WILL GET VALUE ERROR

## 🚀 WHY important for ML:
✅ Combine predictions
✅ Stack features from multiple sources
✅ Split data into train/test batches
✅ Merge labels with data
✅ Prepare input tensors for neural networks


## 🎯 REAL LIFE EXAMPLES:
---


Example 1:

👉 “You trained 3 models → each outputs (100, 1) prediction array
→ Stack them horizontally → final shape (100, 3)”

`final_preds = np.hstack([model1_preds, model2_preds, model3_preds])`

In [ ]:
mdl1=np.random.rand(100,1)
mdl2=np.random.rand(100,1)
mdl3=np.random.rand(100,1)

final_mdl=np.hstack([mdl1,mdl2,mdl3])
print(final_mdl)

Example 2:

👉 “You have image data (N, 28, 28)

👉 You want to flatten each image

👉 Then stack all into (N, 784)”



In [ ]:
img_data_flat = img_data.reshape(img_data.shape[0], -1)
print(img_data_flat.shape)

Example 3:
👉 “You have a dataset (N, 10) — 7 features + 3 labels 

👉 Split into: X = features, Y = labels”

`X = data[:, :7]
Y = data[:, 7:]
`

## 🚀PRACTICE QUESTIONS

In [ ]:
a = np.arange(6).reshape(2, 3)
b = np.ones((2, 3))

# Horizontally stack a and b
# Vertically stack a and b

print(np.hstack([a,b]))

print(np.vstack([a,b]))

# REMEMBER YOU CAN STACK AS MANY ARRAYS AS YOU WANT 

[[0. 1. 2. 1. 1. 1.]
 [3. 4. 5. 1. 1. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [50]:
a = np.arange(16).reshape(4, 4)

# Split a into 2 vertical parts
# Split a into 2 horizontal parts

TOP,BOTTOM=np.vsplit(a,2)
print(TOP,"\n",BOTTOM)

left,right=np.hsplit(a,[1])
print(left,"\n",right)

[[0 1 2 3]
 [4 5 6 7]] 
 [[ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]] 
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [ ]:
preds = [np.random.randn(100, 1) for _ in range(5)]

# Combine into shape (100, 5)
print(np.vstack([preds]))


---
`preds = [np.random.randn(100, 1) for _ in range(5)]
`

👉 This is called a list comprehension in Python:

 It is same as writing:

 `preds = []

  for i in range(5):

    arr = np.random.randn(100, 1)
    
    preds.append(arr)
`


In [ ]:
X = np.random.randn(500, 20)
Y = np.random.randint(0, 2, size=(500, 1))

# Stack X and Y horizontally → final shape = ?
# Then split it back into X and Y
b=np.hstack([X,Y])
print(b.shape)


(500, 21)


### Q5️⃣ EPFL Challenge:

In [84]:
X = np.random.randn(500, 20)
Y = np.random.randint(0, 2, size=(500, 1))

# Stack X and Y horizontally → final shape = ?
# Then split it back into X and Y

a=np.hstack([X,Y])
print(a.shape)
new_X ,new_y=np.hsplit(a,[20])
print(new_X.shape,new_y.shape)

(500, 21)
(500, 20) (500, 1)


# 🏆 MODULE 8: NumPy for Images & Computer Vision

### WHY learn this?
👉 In AI/ML — you work with:

✅ Images (as arrays)

✅ Image batches

✅ RGB vs Grayscale

✅ Channel ordering

✅ Preprocessing (normalize, reshape, transpose)

✅ Feeding into CNNs



### KEY CONCEPTS:

1️⃣ What is a batch?
👉 In Deep Learning — we almost never feed 1 image at a time — too slow!

👉 Instead, we feed a batch of images — say, 32 or 64 images at once.

👉 So:

1 image → shape (H, W, C) → Example: (28,28,1) or (64,64,3)

Batch of N images → shape (N, H, W, C)

If you use 2 instead of 3 for the channel dimension, e.g. `batch = np.random.randn(32, 64, 64, 2)`, it means each image has **2 channels** per pixel instead of 3. This is uncommon for standard images (which are usually grayscale (1 channel) or RGB (3 channels)), but it could represent:

- A custom image format with 2 features per pixel (e.g., two different sensor readings)
- A mask + image pair
- Any data where each pixel has 2 values (not standard RGB)

**In summary:**  
- `3` = RGB (Red, Green, Blue)  
- `1` = Grayscale  
- `2` = Custom/Non-standard (interpretation depends on your data)
👉 Example:

python
 batch of 32 RGB images 64x64:

`batch = np.random.randn(32, 64, 64, 3)`

👉 This is called Batch Dimension → axis 0 = number of images.

WHY?

✅ Faster training

✅ Better gradient estimates

✅ Industry standard in AI/ML

---

2️⃣ What is channel?
👉 For images — "channels" mean color depth:

Grayscale → 1 channel
→ shape (H, W) or (H, W, 1)

RGB → 3 channels (Red, Green, Blue)
→ shape (H, W, 3)

Channels are depth dimension — For example:

`img_rgb.shape = (64, 64, 3)`

👉 Channels = axis 2 here.

---

1️⃣ Grayscale Image → 2D array

Example:

MNIST image → (28, 28)

In [ ]:
img = np.random.randint(0, 256, size=(28, 28), dtype=np.uint8)


2️⃣ RGB Image → 3D array

Shape: (height, width, channels) → channels = 3 (R,G,B)

In [ ]:
img_rgb = np.random.randint(0, 256, size=(64, 64, 3), dtype=np.uint8)


3️⃣ Batch of Images → 4D array

Shape: (batch_size, height, width, channels)

→ 32 images → each 64x64 → 3 channels

In [ ]:
batch = np.random.randint(0, 256, size=(32, 64, 64, 3), dtype=np.uint8)

4️⃣ Transposing images → channel-first vs channel-last

👉 Some frameworks (like PyTorch) expect:

(batch, channels, height, width)

While others (like TensorFlow/Keras) use:

(batch, height, width, channels)

-> TO CHANGE THE DIMENSION OR ORDER U CAN USE THIS FUNCTION
   👉 The function:
   
   `np.transpose(array, new_axes_order)`

In [ ]:
# IN PYTORCH TENSOR FLOW CHANNELS AT AXIS=1 BUT IN TESORFLOW/KERAS IT IS AT AXIS=3 SO TH CHANGE

batch_transposed = np.transpose(batch, (0, 3, 1, 2))


4️⃣ What is Normalization?

👉 Raw image pixel values = 0 to 255 (8-bit)

👉 Neural networks work MUCH better when input is 0 to 1 (small numbers) or normalized.

👉 So:

`img_norm = img / 255.0`
WHY?

✅ Faster learning

✅ More stable gradients

✅ Standard practice in all AI models.

---


### FLATTENING (IMP CONCEPT)

❓ What does "Flatten" mean?

👉 Images are 2D (grayscale) or 3D (RGB) — but ML models need 1D vectors for fully connected layers.

Example:

1. grayscale image = shape (28, 28) → 2D

   Flattened → shape (784,) → 
   
🔍 Code for flattening one image:

In [37]:
img = np.random.randint(0, 256, size=(28, 28,28), dtype=np.uint8)

# Flatten image:
img_flat = img.flatten()

print(img.shape)     # (28, 28)
print(img_flat.shape)  # (784,)

(28, 28, 28)
(21952,)


🔍 Code for flattening a batch of images:

In [ ]:
batch_flat = batch.reshape(batch.shape[0], -1)

print(batch_flat.shape)  # (64, 784)


❓ What is .reshape(batch.shape[0], -1) ?

👉 batch.shape[0] = number of images = 64

👉 -1 means "automatically compute" number of columns.

👉 So:

In [ ]:
batch_flat = batch.reshape(64, 784)


### ⚡ PRACTICE

👉 You have a batch of 32 RGB images (64,64,3):
* Write code to:

1️⃣ Normalize the pixel values to [0,1]

2️⃣ Transpose it to (batch, channels, height, width)

3️⃣ Flatten it into (32, 12288) → because 64643 = 12288

In [7]:
image=np.random.randint(0,240,size=(32,64,64,3))
image=image/255.0 #normalize
a=image.transpose(0,3,1,2) # transposing it to (batch, channels, height, width)
print(a.shape)
b=image.reshape(image.shape[0],-1)
print(b.shape)


(32, 3, 64, 64)
(32, 12288)


👉 You have a batch of 100 grayscale images (28,28):
* Write code to:

1️⃣ Print the batch size

2️⃣ Print shape of first image

3️⃣ Flatten the batch into shape (100, 784)

In [ ]:
batch_gs=np.random.randint(1,100,size=(100,28,28))
print(batch_gs.shape[0])
print(batch_gs.shape([1]))

100


TypeError: 'tuple' object is not callable

# 🔥 MODULE 9: Performance Tricks — Vectorization & Memory

### WHY learn this?

👉 You already know NumPy well — BUT:

👉 Slow code won’t survive in competitions or research labs 🚀

👉 This module will show you how to write FAST, elegant NumPy code that crushes loops 💥

## 💡 Key Concepts:

1️⃣ Vectorization → "No for-loops"

BAD:

In [ ]:
for i in range(100):
    x[i] = x[i] + 10


GOOD:

In [ ]:
x = x + 10

2️⃣ Broadcasting + vectorization → super powerful

--> This is super fast — no loop over rows or columns 🚀

In [ ]:
x = np.random.randn(100, 5)

# Normalize each feature (column)
x_norm = (x - x.mean(axis=0)) / x.std(axis=0)


3️⃣ Avoiding "copy" — In-place operations

In [ ]:
x += 10    # inplace → saves memory

4️⃣ Preallocate arrays instead of appending

BAD:

In [ ]:
arr = []
for i in range(1000):
    arr.append(i)


GOOD:

In [ ]:
arr = np.empty(1000)
for i in range(1000):
    arr[i] = i


5️⃣ Use built-in NumPy functions

✅ ALWAYS prefer built-in functions

👉 Much faster than writing loops.

`np.sum()`

`np.mean()`

`np.dot()`

`np.linalg.norm()`

6️⃣ Memory Efficiency

👉 Use correct data type (dtype) when possible:

→ Less RAM used

→ Faster operations (especially on GPU!)

## 🚀 Real-life examples and Practice:

Q1️⃣ BAD vs GOOD

In [45]:
# BAD:
out = np.arange(12).reshape(3,4)
for i in range(12):
    out[i] = out[i] ** 2

# GOOD:
out = out ** 2
print(out)

IndexError: index 3 is out of bounds for axis 0 with size 3

Q2️⃣ Normalize batch of images (without loop)

Given:batch = np.random.randint(0, 256, size=(64, 64, 64, 3), dtype=np.uint8)


In [ ]:
batch = np.random.randint(0, 256, size=(64, 64, 64, 3), dtype=np.uint8)
batch=batch/255.0
print(batch)

### 🎯 Final EPFL Challenge:


👉 Rewrite using pure NumPy — NO loops 🚀

Given this slow code:

`X = np.random.randn(10000, 10)`

`out = []`

`for i in range(X.shape[0]):`

     `out.append(np.sum(X[i] ** 2))`

`out = np.array(out)`

GOOD-->ANY OF THIS METHOD

In [48]:
X = np.random.randn(10000, 10)
o=X**2
o=o.sum(axis=1)
print(o)
out = np.sum(X**2, axis=1)
print(out)
out1=[np.sum(X[i]**2) for i in range(X.shape[0])]
print(out1)

[13.26907815  3.32744929 12.08720338 ...  8.60555142 18.3550325
 12.47677818]
[13.26907815  3.32744929 12.08720338 ...  8.60555142 18.3550325
 12.47677818]
[13.269078146336572, 3.3274492871930486, 12.087203377341304, 16.10213190366967, 9.310565320763079, 2.524035171273707, 22.46555825713488, 7.980603560614144, 14.589436717444094, 6.398259067861151, 2.2655527440079775, 6.961306406425393, 11.581821103707647, 5.874359199391196, 6.719589621733971, 5.835056913791529, 6.902022240980074, 11.179363916450793, 6.38243653970793, 6.843668006548405, 20.76038916814093, 6.702152403335724, 9.3651941905977, 9.871561089095858, 2.97527960505471, 6.955700752589764, 5.76645980402695, 13.221451604507845, 7.895660212384625, 10.097431394383591, 11.75065895536479, 13.10284361214285, 9.967360545889122, 12.991793859878435, 14.13409518661416, 11.418040125856212, 5.261045784079365, 15.3891162945087, 17.39343138555246, 11.157252539459062, 8.84726482578399, 9.437822874175353, 11.751947134805159, 14.624660627964849, 

BAD

In [49]:
X = np.random.randn(10000, 10)
out = []
for i in range(X.shape[0]):
    out.append(np.sum(X[i] ** 2))
out = np.array(out)
print(out)
# This code computes the sum of squares of each row in X.
# For each row i in X, it calculates np.sum(X[i] ** 2) (i.e., the squared L2 norm of the row).
# The result is a 1D array 'out' of shape (10000,), where each element is the sum of squares of the corresponding row in X.

# Your code:
# out = X**2
# out = X.sum(axis=0)
# does NOT do the same thing.
# - X**2 computes the element-wise square, but does not sum.
# - X.sum(axis=0) sums each column, not the sum of squares per row.
# The correct vectorized version is:


# np.random.randn generates samples from the standard normal distribution,
# which has a mean of 0 and standard deviation of 1.
# The range is theoretically (-inf, +inf), but ~99.7% of values fall between -3 and +3.

[14.68734222  8.27468188  5.86142162 ... 12.46447048 11.17007607
  8.13879416]


# 🚀 MODULE 10: FINAL PROJECT & PRO CHALLENGES

🎯 The Goal:
👉 You are working in an EPFL ML Lab.
👉 You need to process big datasets FAST using NumPy.
👉 You want code that beats 95% of other students in speed, clarity, and memory use.

🔥 Final Concepts You Will Practice:
✅ Full batch image processing
✅ Vectorization tricks
✅ Broadcasting
✅ Transposing
✅ Flattening
✅ Memory efficiency
✅ Kaggle-style problems

---

⚡ CHALLENGE 1: Image Preprocessing Pipeline
You are given:

`batch = np.random.randint(0, 256, size=(128, 32, 32, 3), dtype=np.uint8)`

👉 Shape = (batch, height, width, channels)

👉 This is like a CIFAR-10 mini-batch.

TASK:

✅ Normalize pixels to [0,1]

✅ Transpose to (batch, channels, height, width)

✅ Flatten each image → final shape (128, 3072)

In [ ]:
batch = np.random.randint(0, 256, size=(128, 32, 32, 3), dtype=np.uint8)
normalize_batch=batch/255.0
transpose_batch=batch.transpose(0,3,1,2)
flatten_batch=batch.reshape(batch.shape[0],-1)

print(normalize_batch,"\n",transpose_batch,"\n",flatten_batch)

⚡ CHALLENGE 2: Feature Engineering
You are given:

`X = np.random.randn(5000, 100)   # 5000 samples, 100 features`

TASK:

✅ For each row, compute:

`f(x) = sum( (x_i + 1) ** 2 ) for i = 1 to 100`


👉 Implement in pure NumPy → NO loops 🚀



In [ ]:
X = np.random.randn(5000, 100)   # 5000 samples, 100 features
fx_sum=np.sum((X+1)**2, axis=1)
print(fx_sum)

⚡ CHALLENGE 3: Kaggle-Style Feature Scaling

You are given:`X = np.random.randn(10000, 50)`

TASK:

✅ For each column:

👉 Subtract the mean

👉 Divide by standard deviation

👉 Result: zero-mean, unit-variance features


In [31]:
X = np.random.randn(10000, 50)
X_norm=(X-X.mean(axis=0))/X.std(axis=0)



⚡ FINAL BOSS: EPFL Project Pipeline

You are given:


`batch = np.random.randint(0, 256, size=(512, 64, 64, 3), dtype=np.uint8)`

TASK:

✅ Normalize to [0,1]

✅ Transpose to (batch, channels, height, width)

✅ Compute L2 norm of each image (flattened)

👉 Output shape = (512,) → 1 norm per image

(Hint: L2 norm = sqrt(sum of squares))

In [36]:
batch = np.random.randint(0, 256, size=(512, 64, 64, 3), dtype=np.uint8)
normalize_batch=batch/255.0
transpose_batch=batch.transpose(0,3,1,2)

batch_flat = normalize_batch.reshape(normalize_batch.shape[0], -1)

# L2 norm:
l2_norms = np.sqrt(np.sum(batch_flat ** 2, axis=1))

print(l2_norms.shape)  # should be (512,)
print(l2_norms[:5])    # show first 5 norms


(512,)
[63.86681187 64.30012685 64.10854729 63.44457674 64.39724085]



# 🚀 NUMPY PRO PRACTICE PACK

### 🎯 SECTION 1: Concept Combo Questions

Q1: Create a 3D array (10, 4, 5) →

✅ Swap axes to (10, 5, 4) →

✅ Flatten last two dimensions → shape (10, 20)

In [56]:
thrd_arr=np.random.randint(1,100,size=(10,4,5))
thrd_arr=np.swapaxes(thrd_arr,2,1)
print(thrd_arr.shape)
thrd_arr=thrd_arr.reshape(thrd_arr.shape[0],-1)
print(thrd_arr.shape)

(10, 5, 4)
(10, 20)


Q2: Given:


`X = np.random.randn(1000, 5)`
✅ For each row, compute:

f(x) = sqrt( sum( (x_i + 2)^2 ) )

✅ Use full vectorization (NO loops)

In [65]:
X = np.random.randn(1000, 5)
F_X=np.sqrt(np.sum((X+2)**2,axis=0))
print(F_X)

[70.55030832 72.09220316 71.41624694 69.93795    70.59521462]


Q3: Create 100x100 matrix of random ints (0, 255)

✅ Normalize to [0,1]

✅ Replace all values < 0.3 with 0

✅ Replace all values > 0.7 with 1



In [ ]:
hun_by_hun=np.random.randint(0,255,size=(100,100))
hun_by_hun=hun_by_hun/255.0
hun_by_hun[hun_by_hun<0.3]=0
hun_by_hun[hun_by_hun>0.7]=1
print(hun_by_hun)

### 🎯 SECTION 2: Real-World Projects (LinkedIn + GitHub ready)

PROJECT 1: Image Dataset Preprocessing

`batch = np.random.randint(0, 256, size=(256, 128, 128, 3), dtype=np.uint8)`

✅ Normalize to [0,1]

✅ Transpose to (batch, channels, height, width)

✅ Compute mean pixel value PER channel

✅ Compute L2 norm of each image

✅ Save 5 images to disk using matplotlib

In [69]:
batch = np.random.randint(0, 256, size=(256, 128, 128, 3), dtype=np.uint8)
batch=batch/255.0
batch=np.transpose(batch,(0,3,1,2))
batch_mean=batch.mean(axis=1)
l2_norms = np.sqrt(np.sum(batch ** 2, axis=1))
import matplotlib.pyplot as plt

# Save the first 5 images (convert from (C, H, W) to (H, W, C))
for i in range(5):
    img = batch[i].transpose(1, 2, 0)  # (C, H, W) -> (H, W, C)
    plt.imsave(f'image_{i}.png', img)



PROJECT 2: Feature Engineering for ML


`X = np.random.randn(5000, 50)`
✅ Normalize (zero mean, unit variance)

✅ Compute new features:


f1 = sum( abs(x_i) )

f2 = max(x_i)

f3 = min(x_i)

✅ Stack features into final array → shape (5000, 3)

✅ Save as CSV (use Pandas here)

In [71]:
"""The `abs` function (or `np.abs` for NumPy arrays) returns the absolute value of a number or each element in an array.  
- For a number: `abs(-5)` returns `5`.
- For an array: `np.abs([-2, 0, 3])` returns `[2, 0, 3]`.

It calculates the distance from zero, ignoring the sign. For complex numbers, it returns the magnitude (i.e., `sqrt(real^2 + imag^2)`)."""


'The `abs` function (or `np.abs` for NumPy arrays) returns the absolute value of a number or each element in an array.  \n- For a number: `abs(-5)` returns `5`.\n- For an array: `np.abs([-2, 0, 3])` returns `[2, 0, 3]`.\n\nIt calculates the distance from zero, ignoring the sign. For complex numbers, it returns the magnitude (i.e., `sqrt(real^2 + imag^2)`).'

In [90]:
X = np.random.randn(5000, 50)
X=X/255.0
f1=np.sum(abs(X),axis=1)
f2=np.max(X,axis=1)
f3=np.min(X,axis=1)

stac_k=np.vstack([f1, f2, f3])
stac_k=np.transpose(stac_k)
print(stac_k.shape)



(5000, 3)


# ⭐️ BONUS EXPLANATION: What is ReLU?
→ ReLU = Rectified Linear Unit

→ It is a simple activation function used in Deep Learning:


`ReLU(x) = max(0, x)`

→ It replaces all negative values with 0 — keeps positive values as they are.

Why?

👉 Without ReLU, neural nets become linear — can’t learn complex patterns.

👉 ReLU makes network non-linear → can model real-world data better.

👉 It’s very fast and works well — default in almost all modern neural nets (CNNs, Transformers, etc).

PROJECT 4: Simulate Neural Network Layer

Simulate a dense layer:


`X = np.random.randn(100, 128)    # batch of 100 inputs, 128 features`

`W = np.random.randn(128, 64)     # weights`

`b = np.random.randn(64)          # bias`

✅ Compute output:

`out = X @ W + b`

✅ Apply ReLU activation:

relu_out = np.maximum(0, out)


In [93]:
X = np.random.randn(100, 128)    # batch of 100 inputs, 128 features
W = np.random.randn(128, 64)     # weights
b = np.random.randn(64)          # bias
out = X @ W + b
print(out)
relu_out=np.maximum(0,out)
print(relu_out)

[[ -1.87424249  12.21397882  26.60231822 ...   5.54046049  17.5221712
    2.35868452]
 [ -3.58774411  19.09219601  16.01501492 ...  -1.76043255  -9.83020611
   16.5521907 ]
 [ -1.40645556   9.34801866   6.49442393 ...   6.77636689  -6.19885966
    0.56693603]
 ...
 [ -4.37099944 -14.12008371   7.04744439 ...  10.19876926 -18.3958282
   15.88452583]
 [ -8.37528241  -2.89735092   4.37804887 ...  -9.87497791  -1.6087005
   -6.11107044]
 [ 23.26856113 -10.54648259   1.39079392 ... -11.62362527  -1.66826825
   -7.62988937]]
[[ 0.         12.21397882 26.60231822 ...  5.54046049 17.5221712
   2.35868452]
 [ 0.         19.09219601 16.01501492 ...  0.          0.
  16.5521907 ]
 [ 0.          9.34801866  6.49442393 ...  6.77636689  0.
   0.56693603]
 ...
 [ 0.          0.          7.04744439 ... 10.19876926  0.
  15.88452583]
 [ 0.          0.          4.37804887 ...  0.          0.
   0.        ]
 [23.26856113  0.          1.39079392 ...  0.          0.
   0.        ]]
